"""new_catetories

Revision ID: 53ac8bb8d28a
Revises: b96c2f92b6dc
Create Date: 2024-12-15 09:26:42.245019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ac8bb8d28a'
down_revision = 'b96c2f92b6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent', new_column_name='parent_id')
    op.drop_constraint('categories_parent_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent_id', new_column_name='parent')
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_fkey', 'categories', 'categories', ['parent'], ['id'])
    # ### end Alembic commands ###
